FROM debian

ADD debian.list /etc/apt/sources.list.d/
ADD index.html /var/www/Petya.com/
ADD img.jpg /var/www/Petya.com/img/

RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p Petya.com/img && \
    chmod -R 754 /var/www/Petya.com/ && \
    useradd Petr && groupadd Karyaka && usermod -a -G Karyaka Petr && \
    chown -R Petr:Karyaka /var/www/Petya.com && \
    sed -i 's$/var/www/html$/var/www/Petya.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Petr/g' /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]